#!/bin/sh -ex

if [ -z "$LOGGING" ]
then 
   # write a log, in case sth goes wrong
   LOGGING=1 /bin/sh -e "$0" "$@" > /mnt/HD/HD_a2/ffp.log 2>&1
   exit 0
fi

# switch to safe working directory on ramdisk
cd /

# Boot on USB Key (1 or 0)
USB_BOOT=1
DISTRIB=squeeze-armel

HD_MNT=/mnt/HD/HD_a2
USB_MNT=/mnt/USB/HD_c1

# Tar file with debian bootstrap
SOURCE=$HD_MNT/$DISTRIB.tar
# Directory where decompress debian
[ "$USB_BOOT" = "1" ] && DEST=$USB_MNT || DEST=$HD_MNT

# Final chroot directory (tar file should have $DISTRIB directory)
CHROOT=$DEST/$DISTRIB

# usbmount script to be patched (1 or 0)
PATCH_USBMOUNT=1
USBMOUNT_FILE=/usr/local/modules/script/usbmount
CONFIG_DIR=/usr/local/config
RCINIT_FILE=$CONFIG_DIR/rc.init.sh

echo "`date '+[%d/%m/%Y %R]'` ------ Stating DEBIAN DNS-320/325 ------"
echo "Starting on: $CHROOT"

if [ "$PATCH_USBMOUNT" = "1" ]; then
   echo "Patching USB mount..."

   echo "Create $CONFIG_DIR/usbpatch.sh"
   cat <<EOF > $CONFIG_DIR/usbpatch.sh
#!/bin/sh -ex
echo "Patching $USBMOUNT_FILE: disable chmod -R a+w on USB mount..."
cp -pf $USBMOUNT_FILE /tmp/`basename $USBMOUNT_FILE`
sed -i 's/chmod -R/#chmod -R/' /tmp/`basename $USBMOUNT_FILE`
mount -n --bind /tmp/`basename $USBMOUNT_FILE` $USBMOUNT_FILE
echo "$USBMOUNT_FILE patched"
EOF

   [ ! -f $RCINIT_FILE.bak ] \
      && "Backup $RCINIT_FILE to $RCINIT_FILE.bak" \
      && cp -pf $RCINIT_FILE $RCINIT_FILE.bak

   grep 'usbpatch.sh' $RCINIT_FILE \
     && echo "$RCINIT_FILE already patched" \
     || echo "sh -ex $CONFIG_DIR/usbpatch.sh > $CONFIG_DIR/usbpatch.log" >> $RCINIT_FILE

   # cat $RCINIT_FILE
   # cat $CONFIG_DIR/usbpatch.sh
   # cat /usr/local/config/usbpatch.log || true
   # cat $USBMOUNT_FILE | grep 'chmod -R'
   echo "USB mount patched..."
else
   echo "Restore backup from /usr/local/modules/default/rc.init.sh"
   cp -pf /usr/local/modules/default/rc.init.sh $CONFIG_DIR
   [ -f $CONFIG_DIR/usbpatch.sh ] && echo "Remove $CONFIG_DIR/usbpatch.sh" && rm $CONFIG_DIR/usbpatch.sh
fi

if [ "$USB_BOOT" = "1" ]; then
   echo "Waiting USB Key $USB_MNT to be mounted"
   local i=1; until df | grep $USB_MNT; do i=$((i*2)); echo sleep $i; sleep $i; done
   echo "USB Key $USB_MNT mounted"

   # ls -la $USB_MNT
fi

# Risky!
[ -f $CHROOT.reinstall ] && echo "Remove $CHROOT" && echo rm -rf $CHROOT $CHROOT.reinstall

if [ ! -d $CHROOT ]; then
   echo "Installing on $DEST..."
   tar xf $SOURCE -C $DEST
   $CHROOT/usr/sbin/chroot $CHROOT bash -c 'echo "root:dlink" | chpasswd'

   # ls -la $CHROOT
fi

# Correction devices/droits/groupes/repertoires
[ ! -e /dev/random ] && mknod -m 0444 /dev/random c 1 8
[ ! -e /dev/ptmx ]   && mknod -m 0666 /dev/ptmx   c 5 2
mkdir -p /var/run /var/log /dev/pts
chmod 0666 /dev/tty /dev/null ; chmod 1777 /tmp
! grep -wq utmp /etc/group && echo 'utmp:!:22:' >> /etc/group
! mount | grep -wq devpts  && mount -t devpts devpts /dev/pts
touch /var/run/utmp /var/log/btmp /var/log/lastlog /var/log/wtmp

# Mount repertoires systemes dans environement chroote
mkdir -p $CHROOT/mnt/root $CHROOT/mnt/config $CHROOT/mnt/modules
mount -n --bind / $CHROOT/mnt/root
mount -n --bind /usr/local/config $CHROOT/mnt/config || true
mount -n --bind /usr/local/modules $CHROOT/mnt/modules || true
mount -n --bind /dev $CHROOT/dev
mount -n --bind /sys  $CHROOT/sys
mount -n --bind /proc $CHROOT/proc
for DISK in `mount|awk '$3~"/mnt/"{print $3}'`; do
   if [ -d $DISK ] ; then mkdir -p $CHROOT/$DISK ; mount -n --bind $DISK $CHROOT/$DISK ; fi
done

# Copie parametres specifiques du NAS dans environnement chroote
cp -f /proc/mounts $CHROOT/etc/mtab ; rm -f $CHROOT/etc/fstab
touch $CHROOT/etc/fstab ; cp -f /etc/resolv.conf $CHROOT/etc
hostname > $CHROOT/etc/hostname ; cp -f /etc/hosts $CHROOT/etc

# Lancement environnement chroote
# chmod -R 600 $CHROOT/etc/ssh/ $CHROOT/var/run/sshd
# chmod 777 $CHROOT/boot/linuxrc $CHROOT/boot
# $CHROOT/boot/chroot $CHROOT /boot/linuxrc
# $HD_MNT/chroot $CHROOT service ssh start
$CHROOT/usr/sbin/chroot $CHROOT service ssh start

echo "`date '+[%d/%m/%Y %R]'` ------ Fin Demarrage DEBIAN DNS-320/325 ------"
