#!/bin/sh

# switch to safe working directory on ramdisk
cd /

# Boot on USB Key (1 or 0)
USB_BOOT=1
DISTRIB=squeeze-armel

HD_MNT=/mnt/HD/HD_a2
USB_MNT=/mnt/USB/HD_c1

# Tar file with debian bootstrap
SOURCE=$HD_MNT/$DISTRIB.tar
# Directory where decompress debian
[ "$USB_BOOT" = "1" ] && DEST=$USB_MNT || DEST=$HD_MNT

# Final chroot directory (tar file should have $DISTRIB directory)
CHROOT=$DEST/$DISTRIB

# write a log, in case sth goes wrong
rm $HD_MNT/ffp.log
exec >> $HD_MNT/ffp.log 2>&1

printf "\n\n`date '+[%d/%m/%Y %R]'` ------ Stating DEBIAN DNS-320/325 ------\n"
printf "Starting on: $CHROOT\n"

if [ "$USB_BOOT" = "1" ]; then
   printf "\nWaiting USB Key $USB_MNT to be mounted\n"
   local i=1; until df | grep $USB_MNT; do i=$((i*2)); echo sleep $i; sleep $i; done
   printf "USB Key $USB_MNT mounted\n"

   # ls -la $USB_MNT >> $HD_MNT/ffp.log 2>&1
fi

# Risky!
# [ -f $CHROOT.reinstall ] && prinf "Remove $CHROOT" && rm -rf $CHROOT $CHROOT.reinstall >> $HD_MNT/ffp.log 2>&1

if [ ! -d $CHROOT ]; then
   printf "\nInstalling on $DEST...\n"
   tar xf $SOURCE -C $DEST >> $HD_MNT/ffp.log 2>&1
   $CHROOT/usr/sbin/chroot $CHROOT bash -c 'echo "root:dlink" | chpasswd' >> $HD_MNT/ffp.log 2>&1
fi

# Correction devices/droits/groupes/repertoires
[ ! -e /dev/random ] && mknod -m 0444 /dev/random c 1 8
[ ! -e /dev/ptmx ]   && mknod -m 0666 /dev/ptmx   c 5 2
mkdir -p /var/run /var/log /dev/pts
chmod 0666 /dev/tty /dev/null ; chmod 1777 /tmp
! grep -wq utmp /etc/group && echo 'utmp:!:22:' >> /etc/group
! mount | grep -wq devpts  && mount -t devpts devpts /dev/pts
touch /var/run/utmp /var/log/btmp /var/log/lastlog /var/log/wtmp

# Mount repertoires systemes dans environement chroote
mkdir -p $CHROOT/mnt/root; mount -n --bind / $CHROOT/mnt/root ; mount -n --bind /dev  $CHROOT/dev
mount -n --bind /sys  $CHROOT/sys  ; mount -n --bind /proc $CHROOT/proc
for DISK in `mount|awk '$3~"/mnt/"{print $3}'`; do
   if [ -d $DISK ] ; then mkdir -p $CHROOT/$DISK ; mount -n --bind $DISK $CHROOT/$DISK ; fi
done

# Copie parametres specifiques du NAS dans environnement chroote
cp -f /proc/mounts $CHROOT/etc/mtab ; rm -f $CHROOT/etc/fstab
touch $CHROOT/etc/fstab ; cp -f /etc/resolv.conf $CHROOT/etc
hostname > $CHROOT/etc/hostname ; cp -f /etc/hosts $CHROOT/etc

# Lancement environnement chroote
chmod 600 $CHROOT/etc/ssh/* $CHROOT/var/run/sshd
# chmod 777 $CHROOT/boot/linuxrc $CHROOT/boot
# $CHROOT/boot/chroot $CHROOT /boot/linuxrc
# $HD_MNT/chroot $CHROOT service ssh start
$CHROOT/usr/sbin/chroot $CHROOT service ssh start >> $HD_MNT/ffp.log 2>&1
printf "`date '+[%d/%m/%Y %R]'` ------ Fin Demarrage DEBIAN DNS-320/325 ------\n"
